### ISSUE TITLE
Wrong epd_type

### ISSUE THREAD

**Issue by gigac280** [btc-ticker/btc-ticker#10]
When try to change my screen to 7.5 inch, i get error 

May 15 16:29:56 eink run.sh[933]: Wrong epd_type
May 15 16:29:56 eink run.sh[933]: Traceback (most recent call last):
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 439, in <module>
May 15 16:29:56 eink run.sh[933]:     main(config, args.config)
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 212, in main
May 15 16:29:56 eink run.sh[933]:     w, h, mirror = get_display_size(epd_type)
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 132, in get_display_size
May 15 16:29:56 eink run.sh[933]:     epd, mirror, width_first, Use4Gray, Init4Gray, FullUpdate = get_epd(epd_type)
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 127, in get_epd
May 15 16:29:56 eink run.sh[933]:     raise Exception("Wrong epd_type")
May 15 16:29:56 eink run.sh[933]: Exception: Wrong epd_type
May 15 16:29:56 eink run.sh[933]: Traceback (most recent call last):
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 439, in <module>
May 15 16:29:56 eink run.sh[933]:     main(config, args.config)
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 212, in main
May 15 16:29:56 eink run.sh[933]:     w, h, mirror = get_display_size(epd_type)
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 132, in get_display_size
May 15 16:29:56 eink run.sh[933]:     epd, mirror, width_first, Use4Gray, Init4Gray, FullUpdate = get_epd(epd_type)
May 15 16:29:56 eink run.sh[933]:   File "/home/admin/tickerEink.py", line 127, in get_epd
May 15 16:29:56 eink run.sh[933]:     raise Exception("Wrong epd_type")
May 15 16:29:56 eink run.sh[933]: Exception: Wrong epd_type
May 15 16:29:56 eink systemd[1]: btcticker.service: Main process exited, code=exited, status=1/FAILURE
May 15 16:29:56 eink systemd[1]: btcticker.service: Failed with result 'exit-code'.
May 15 16:29:56 eink systemd[1]: Failed to start btcticker.

Only what i do is unhash epd_type = 7in5_V2

**Comment by gigac280** [comment]
Now get this... RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
Exception ignored in: <function GPIOBase.__del__ at 0x71b3a2b0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 155, in __del__
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 444, in close
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 240, in close
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 568, in close
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 115, in close
  File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 432, in <lambda>
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 307, in _set_when_changed
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 232, in _disable_event_detect
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
