### ISSUE TITLE
congecko complains on rate limit

### ISSUE THREAD

**Issue by MJ-LAMARC** [btc-ticker/btc-ticker#8]
Since 15. Dec 2023:

Dec 16 10:11:55 raspberrypi systemd[1]: Starting btcticker...
Dec 16 10:12:10 raspberrypi run.sh[1917]: Matplotlib is building the font cache; this may take a moment.
Dec 16 10:12:55 raspberrypi systemd[1]: Started btcticker.
Dec 16 10:12:56 raspberrypi run.sh[1917]: {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
Dec 16 10:12:56 raspberrypi run.sh[1917]: 'ValueError' object has no attribute 'split'
Dec 16 10:12:56 raspberrypi run.sh[1917]: Traceback (most recent call last):
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/api.py", line 29, in __request
Dec 16 10:12:56 raspberrypi run.sh[1917]:     response.raise_for_status()
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 1022, in raise_for_status
Dec 16 10:12:56 raspberrypi run.sh[1917]:     raise HTTPError(http_error_msg, response=self)
Dec 16 10:12:56 raspberrypi run.sh[1917]: requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=eur&days=1
Dec 16 10:12:56 raspberrypi run.sh[1917]: During handling of the above exception, another exception occurred:
Dec 16 10:12:56 raspberrypi run.sh[1917]: Traceback (most recent call last):
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 234, in fullupdate
Dec 16 10:12:56 raspberrypi run.sh[1917]:     ticker.refresh()
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/ticker.py", line 88, in refresh
Dec 16 10:12:56 raspberrypi run.sh[1917]:     self.price.refresh()
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/price.py", line 24, in refresh
Dec 16 10:12:56 raspberrypi run.sh[1917]:     self.timeseriesstack = self.coingecko.getHistoryPrice(self.fiat)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/coingecko.py", line 34, in getHistoryPrice
Dec 16 10:12:56 raspberrypi run.sh[1917]:     rawtimeseries = self.cg.get_coin_market_chart_by_id(self.whichcoin, currency, self.days_ago)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/utils.py", line 12, in input_args
Dec 16 10:12:56 raspberrypi run.sh[1917]:     return func(*args, **kwargs)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/api.py", line 169, in get_coin_market_chart_by_id
Dec 16 10:12:56 raspberrypi run.sh[1917]:     return self.__request(api_url)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/api.py", line 36, in __request
Dec 16 10:12:56 raspberrypi run.sh[1917]:     raise ValueError(content)
Dec 16 10:12:56 raspberrypi run.sh[1917]: ValueError: {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
Dec 16 10:12:56 raspberrypi run.sh[1917]: During handling of the above exception, another exception occurred:
Dec 16 10:12:56 raspberrypi run.sh[1917]: Traceback (most recent call last):
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 359, in <module>
Dec 16 10:12:56 raspberrypi run.sh[1917]:     main(config, args.config)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 328, in main
Dec 16 10:12:56 raspberrypi run.sh[1917]:     lastcoinfetch=fullupdate(mode_list[last_mode_ind], days_list[days_ind], layout_list[last_layout_ind], inverted)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 241, in fullupdate
Dec 16 10:12:56 raspberrypi run.sh[1917]:     showmessage(epd_type, ticker, e, mirror, inverted)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 141, in showmessage
Dec 16 10:12:56 raspberrypi run.sh[1917]:     ticker.build_message(message, mirror=mirror)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/ticker.py", line 151, in build_message
Dec 16 10:12:56 raspberrypi run.sh[1917]:     message_per_line = message.split("\n")
Dec 16 10:12:56 raspberrypi run.sh[1917]: AttributeError: 'ValueError' object has no attribute 'split'
Dec 16 10:12:56 raspberrypi run.sh[1917]: Traceback (most recent call last):
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/api.py", line 29, in __request
Dec 16 10:12:56 raspberrypi run.sh[1917]:     response.raise_for_status()
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 1022, in raise_for_status
Dec 16 10:12:56 raspberrypi run.sh[1917]:     raise HTTPError(http_error_msg, response=self)
Dec 16 10:12:56 raspberrypi run.sh[1917]: requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=eur&days=1
Dec 16 10:12:56 raspberrypi run.sh[1917]: During handling of the above exception, another exception occurred:
Dec 16 10:12:56 raspberrypi run.sh[1917]: Traceback (most recent call last):
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 234, in fullupdate
Dec 16 10:12:56 raspberrypi run.sh[1917]:     ticker.refresh()
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/ticker.py", line 88, in refresh
Dec 16 10:12:56 raspberrypi run.sh[1917]:     self.price.refresh()
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/price.py", line 24, in refresh
Dec 16 10:12:56 raspberrypi run.sh[1917]:     self.timeseriesstack = self.coingecko.getHistoryPrice(self.fiat)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/coingecko.py", line 34, in getHistoryPrice
Dec 16 10:12:56 raspberrypi run.sh[1917]:     rawtimeseries = self.cg.get_coin_market_chart_by_id(self.whichcoin, currency, self.days_ago)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/utils.py", line 12, in input_args
Dec 16 10:12:56 raspberrypi run.sh[1917]:     return func(*args, **kwargs)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/api.py", line 169, in get_coin_market_chart_by_id
Dec 16 10:12:56 raspberrypi run.sh[1917]:     return self.__request(api_url)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/pycoingecko-2.2.0-py3.9.egg/pycoingecko/api.py", line 36, in __request
Dec 16 10:12:56 raspberrypi run.sh[1917]:     raise ValueError(content)
**Dec 16 10:12:56 raspberrypi run.sh[1917]: ValueError: {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}**
Dec 16 10:12:56 raspberrypi run.sh[1917]: During handling of the above exception, another exception occurred:
Dec 16 10:12:56 raspberrypi run.sh[1917]: Traceback (most recent call last):
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 359, in <module>
Dec 16 10:12:56 raspberrypi run.sh[1917]:     main(config, args.config)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 328, in main
Dec 16 10:12:56 raspberrypi run.sh[1917]:     lastcoinfetch=fullupdate(mode_list[last_mode_ind], days_list[days_ind], layout_list[last_layout_ind], inverted)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 241, in fullupdate
Dec 16 10:12:56 raspberrypi run.sh[1917]:     showmessage(epd_type, ticker, e, mirror, inverted)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/home/admin/tickerEink.py", line 141, in showmessage
Dec 16 10:12:56 raspberrypi run.sh[1917]:     ticker.build_message(message, mirror=mirror)
Dec 16 10:12:56 raspberrypi run.sh[1917]:   File "/usr/local/lib/python3.9/dist-packages/btc_ticker-0.5.0-py3.9.egg/btcticker/ticker.py", line 151, in build_message
Dec 16 10:12:56 raspberrypi run.sh[1917]:     message_per_line = message.split("\n")
Dec 16 10:12:56 raspberrypi run.sh[1917]: AttributeError: 'ValueError' object has no attribute 'split'
Dec 16 10:12:58 raspberrypi systemd[1]: btcticker.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 10:12:58 raspberrypi systemd[1]: btcticker.service: Failed with result 'exit-code'.

**Comment by machadommm** [comment]
Yeah, same problem here. I am looking for the possibility to put ID token from CoinGecko. Maybe the develper help us...
